import { Router } from "express";

const router = Router();

router.get("/", (_req, res) => {
  // In a real app, this might be generated by an LLM or pulled from a CMS
  const snapshot = {
    date: new Date().toISOString(),
    title: "The Creative World Snapshot",
    summary: "A curated view of the intersection between design, technology, and human systems.",
    highlights: [
      {
        title: "Minimalist Systems",
        description: "The shift toward 'quiet' software that respects human attention."
      },
      {
        title: "AI as a Material",
        description: "Treating large models as a design material rather than just a feature."
      },
      {
        title: "Digital Gardens",
        description: "The resurgence of personal, non-performative web spaces."
      }
    ],
    vibe: "Focused, intentional, and slightly experimental."
  };

  res.json(snapshot);
});

export default router;
